// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

type PickContentRelationshipFieldData<
  TRelationship extends
    | prismic.CustomTypeModelFetchCustomTypeLevel1
    | prismic.CustomTypeModelFetchCustomTypeLevel2
    | prismic.CustomTypeModelFetchGroupLevel1
    | prismic.CustomTypeModelFetchGroupLevel2,
  TData extends Record<
    string,
    | prismic.AnyRegularField
    | prismic.GroupField
    | prismic.NestedGroupField
    | prismic.SliceZone
  >,
  TLang extends string,
> =
  // Content relationship fields
  {
    [TSubRelationship in Extract<
      TRelationship["fields"][number],
      prismic.CustomTypeModelFetchContentRelationshipLevel1
    > as TSubRelationship["id"]]: ContentRelationshipFieldWithData<
      TSubRelationship["customtypes"],
      TLang
    >;
  } & // Group
  {
    [TGroup in Extract<
      TRelationship["fields"][number],
      | prismic.CustomTypeModelFetchGroupLevel1
      | prismic.CustomTypeModelFetchGroupLevel2
    > as TGroup["id"]]: TData[TGroup["id"]] extends prismic.GroupField<
      infer TGroupData
    >
      ? prismic.GroupField<
          PickContentRelationshipFieldData<TGroup, TGroupData, TLang>
        >
      : never;
  } & // Other fields
  {
    [TFieldKey in Extract<
      TRelationship["fields"][number],
      string
    >]: TFieldKey extends keyof TData ? TData[TFieldKey] : never;
  };

type ContentRelationshipFieldWithData<
  TCustomType extends
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel1 | string)[]
    | readonly (prismic.CustomTypeModelFetchCustomTypeLevel2 | string)[],
  TLang extends string = string,
> = {
  [ID in Exclude<
    TCustomType[number],
    string
  >["id"]]: prismic.ContentRelationshipField<
    ID,
    TLang,
    PickContentRelationshipFieldData<
      Extract<TCustomType[number], { id: ID }>,
      Extract<prismic.Content.AllDocumentTypes, { type: ID }>["data"],
      TLang
    >
  >;
}[Exclude<TCustomType[number], string>["id"]];

type HomePageDocumentDataSlicesSlice = CenteredIntroSearchSlice;

/**
 * Content for home_page documents
 */
interface HomePageDocumentData {
  /**
   * Slice Zone field in *home_page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: home_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<HomePageDocumentDataSlicesSlice>;
}

/**
 * home_page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomePageDocumentData>,
    "home_page",
    Lang
  >;

type LayoutDesktopDocumentDataSlicesSlice = CenteredIntroSearchSlice;

/**
 * Content for Layout Desktop documents
 */
interface LayoutDesktopDocumentData {
  /**
   * Slice Zone field in *Layout Desktop*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: layout_desktop.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<LayoutDesktopDocumentDataSlicesSlice> /**
   * Meta Title field in *Layout Desktop*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: layout_desktop.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Layout Desktop*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: layout_desktop.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Layout Desktop*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: layout_desktop.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Layout Desktop document from Prismic
 *
 * - **API ID**: `layout_desktop`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type LayoutDesktopDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<LayoutDesktopDocumentData>,
    "layout_desktop",
    Lang
  >;

type WeatherDetailPageDocumentDataSlicesSlice =
  | SearchBarSlice
  | WeatherForecastSlice
  | WeatherDetailListSlice
  | WeatherOverviewSlice;

/**
 * Content for Weather Detail Page documents
 */
interface WeatherDetailPageDocumentData {
  /**
   * Slice Zone field in *Weather Detail Page*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: weather_detail_page.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<WeatherDetailPageDocumentDataSlicesSlice>;
}

/**
 * Weather Detail Page document from Prismic
 *
 * - **API ID**: `weather_detail_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WeatherDetailPageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<WeatherDetailPageDocumentData>,
    "weather_detail_page",
    Lang
  >;

type WeatherInformationDocumentDataSlicesSlice =
  | WeatherDetailListSlice
  | WeatherOverviewSlice;

/**
 * Content for Weather Information documents
 */
interface WeatherInformationDocumentData {
  /**
   * Slice Zone field in *Weather Information*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: weather_information.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/slices
   */
  slices: prismic.SliceZone<WeatherInformationDocumentDataSlicesSlice> /**
   * Meta Title field in *Weather Information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: weather_information.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Weather Information*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: weather_information.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Weather Information*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: weather_information.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Weather Information document from Prismic
 *
 * - **API ID**: `weather_information`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/content-modeling
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WeatherInformationDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<WeatherInformationDocumentData>,
    "weather_information",
    Lang
  >;

export type AllDocumentTypes =
  | HomePageDocument
  | LayoutDesktopDocument
  | WeatherDetailPageDocument
  | WeatherInformationDocument;

/**
 * Primary content in *CenteredIntroSearch → Default → Primary*
 */
export interface CenteredIntroSearchSliceDefaultPrimary {
  /**
   * Logo field in *CenteredIntroSearch → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: centered_intro_search.default.primary.logo
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  logo: prismic.ImageField<never>;

  /**
   * Title field in *CenteredIntroSearch → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: centered_intro_search.default.primary.heading
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  heading: prismic.RichTextField;

  /**
   * Subtitle field in *CenteredIntroSearch → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: centered_intro_search.default.primary.subtitle
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  subtitle: prismic.RichTextField;

  /**
   * Search Placeholder field in *CenteredIntroSearch → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: centered_intro_search.default.primary.search_placeholder
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  search_placeholder: prismic.KeyTextField;
}

/**
 * Default variation for CenteredIntroSearch Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard intro with logo, heading, subtitle, and search bar.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CenteredIntroSearchSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<CenteredIntroSearchSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *CenteredIntroSearch*
 */
type CenteredIntroSearchSliceVariation = CenteredIntroSearchSliceDefault;

/**
 * CenteredIntroSearch Shared Slice
 *
 * - **API ID**: `centered_intro_search`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type CenteredIntroSearchSlice = prismic.SharedSlice<
  "centered_intro_search",
  CenteredIntroSearchSliceVariation
>;

/**
 * Primary content in *SearchBar → With Icon → Primary*
 */
export interface SearchBarSliceWithIconPrimary {
  /**
   * cloud_Icon field in *SearchBar → With Icon → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: search_bar.with_icon.primary.icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;

  /**
   * Placeholder Text field in *SearchBar → With Icon → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: search_bar.with_icon.primary.placeholder
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  placeholder: prismic.KeyTextField;
}

/**
 * With Icon variation for SearchBar Slice
 *
 * - **API ID**: `with_icon`
 * - **Description**: Search bar includes a leading icon and a placeholder text input.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SearchBarSliceWithIcon = prismic.SharedSliceVariation<
  "with_icon",
  Simplify<SearchBarSliceWithIconPrimary>,
  never
>;

/**
 * Slice variation for *SearchBar*
 */
type SearchBarSliceVariation = SearchBarSliceWithIcon;

/**
 * SearchBar Shared Slice
 *
 * - **API ID**: `search_bar`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type SearchBarSlice = prismic.SharedSlice<
  "search_bar",
  SearchBarSliceVariation
>;

/**
 * Item in *WeatherDetailList → Default → Primary → Weather Items*
 */
export interface WeatherDetailListSliceDefaultPrimaryWeatherItemsItem {
  /**
   * Label field in *WeatherDetailList → Default → Primary → Weather Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: weather_detail_list.default.primary.weather_items[].label
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  label: prismic.KeyTextField;

  /**
   * Value field in *WeatherDetailList → Default → Primary → Weather Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: weather_detail_list.default.primary.weather_items[].value
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  value: prismic.KeyTextField;

  /**
   * Unit field in *WeatherDetailList → Default → Primary → Weather Items*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: weather_detail_list.default.primary.weather_items[].unit
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  unit: prismic.KeyTextField;

  /**
   * Icon field in *WeatherDetailList → Default → Primary → Weather Items*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: weather_detail_list.default.primary.weather_items[].icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  icon: prismic.ImageField<never>;
}

/**
 * Primary content in *WeatherDetailList → Default → Primary*
 */
export interface WeatherDetailListSliceDefaultPrimary {
  /**
   * Section Title field in *WeatherDetailList → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: weather_detail_list.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * Weather Items field in *WeatherDetailList → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: weather_detail_list.default.primary.weather_items[]
   * - **Documentation**: https://prismic.io/docs/fields/repeatable-group
   */
  weather_items: prismic.GroupField<
    Simplify<WeatherDetailListSliceDefaultPrimaryWeatherItemsItem>
  >;
}

/**
 * Default variation for WeatherDetailList Slice
 *
 * - **API ID**: `default`
 * - **Description**: Displays a static list of weather details with associated labels, values, and units. Suitable for showing key weather metrics for a given day.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WeatherDetailListSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WeatherDetailListSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WeatherDetailList*
 */
type WeatherDetailListSliceVariation = WeatherDetailListSliceDefault;

/**
 * WeatherDetailList Shared Slice
 *
 * - **API ID**: `weather_detail_list`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WeatherDetailListSlice = prismic.SharedSlice<
  "weather_detail_list",
  WeatherDetailListSliceVariation
>;

/**
 * Primary content in *WeatherForecast → Default → Primary*
 */
export interface WeatherForecastSliceDefaultPrimary {
  /**
   * Section Title field in *WeatherForecast → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: weather_forecast.default.primary.section_title
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  section_title: prismic.KeyTextField;

  /**
   * rainy cloud weather field in *WeatherForecast → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: weather_forecast.default.primary.rainy_weather
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  rainy_weather: prismic.ImageField<never>;

  /**
   * cloud icon field in *WeatherForecast → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: weather_forecast.default.primary.cloud_icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  cloud_icon: prismic.ImageField<never>;

  /**
   * sunny icon field in *WeatherForecast → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: weather_forecast.default.primary.sunny_icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  sunny_icon: prismic.ImageField<never>;

  /**
   * sun cloud icon field in *WeatherForecast → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: weather_forecast.default.primary.sun_cloud_icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  sun_cloud_icon: prismic.ImageField<never>;

  /**
   * cloud storm icon field in *WeatherForecast → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: weather_forecast.default.primary.cloud_storm_icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  cloud_storm_icon: prismic.ImageField<never>;
}

/**
 * Default variation for WeatherForecast Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default display for a weather forecast with a fixed number of days and forecast details per day.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WeatherForecastSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WeatherForecastSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WeatherForecast*
 */
type WeatherForecastSliceVariation = WeatherForecastSliceDefault;

/**
 * WeatherForecast Shared Slice
 *
 * - **API ID**: `weather_forecast`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WeatherForecastSlice = prismic.SharedSlice<
  "weather_forecast",
  WeatherForecastSliceVariation
>;

/**
 * Primary content in *WeatherOverview → Default → Primary*
 */
export interface WeatherOverviewSliceDefaultPrimary {
  /**
   * Location field in *WeatherOverview → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: weather_overview.default.primary.location
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  location: prismic.KeyTextField;

  /**
   * Date field in *WeatherOverview → Default → Primary*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: weather_overview.default.primary.date_label
   * - **Documentation**: https://prismic.io/docs/fields/rich-text
   */
  date_label: prismic.RichTextField;

  /**
   * Time field in *WeatherOverview → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: weather_overview.default.primary.time
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  time: prismic.KeyTextField;

  /**
   * Current Temperature field in *WeatherOverview → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: weather_overview.default.primary.current_temperature
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  current_temperature: prismic.KeyTextField;

  /**
   * Min/Max Temperatures field in *WeatherOverview → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: weather_overview.default.primary.min_max_temperatures
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  min_max_temperatures: prismic.KeyTextField;

  /**
   * Weather Description field in *WeatherOverview → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: weather_overview.default.primary.weather_description
   * - **Documentation**: https://prismic.io/docs/fields/text
   */
  weather_description: prismic.KeyTextField;

  /**
   * Weather Icon field in *WeatherOverview → Default → Primary*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: weather_overview.default.primary.weather_icon
   * - **Documentation**: https://prismic.io/docs/fields/image
   */
  weather_icon: prismic.ImageField<never>;
}

/**
 * Default variation for WeatherOverview Slice
 *
 * - **API ID**: `default`
 * - **Description**: Standard weather summary card with primary weather information and visual indicator.
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WeatherOverviewSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WeatherOverviewSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *WeatherOverview*
 */
type WeatherOverviewSliceVariation = WeatherOverviewSliceDefault;

/**
 * WeatherOverview Shared Slice
 *
 * - **API ID**: `weather_overview`
 * - **Description**: *None*
 * - **Documentation**: https://prismic.io/docs/slices
 */
export type WeatherOverviewSlice = prismic.SharedSlice<
  "weather_overview",
  WeatherOverviewSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      HomePageDocument,
      HomePageDocumentData,
      HomePageDocumentDataSlicesSlice,
      LayoutDesktopDocument,
      LayoutDesktopDocumentData,
      LayoutDesktopDocumentDataSlicesSlice,
      WeatherDetailPageDocument,
      WeatherDetailPageDocumentData,
      WeatherDetailPageDocumentDataSlicesSlice,
      WeatherInformationDocument,
      WeatherInformationDocumentData,
      WeatherInformationDocumentDataSlicesSlice,
      AllDocumentTypes,
      CenteredIntroSearchSlice,
      CenteredIntroSearchSliceDefaultPrimary,
      CenteredIntroSearchSliceVariation,
      CenteredIntroSearchSliceDefault,
      SearchBarSlice,
      SearchBarSliceWithIconPrimary,
      SearchBarSliceVariation,
      SearchBarSliceWithIcon,
      WeatherDetailListSlice,
      WeatherDetailListSliceDefaultPrimaryWeatherItemsItem,
      WeatherDetailListSliceDefaultPrimary,
      WeatherDetailListSliceVariation,
      WeatherDetailListSliceDefault,
      WeatherForecastSlice,
      WeatherForecastSliceDefaultPrimary,
      WeatherForecastSliceVariation,
      WeatherForecastSliceDefault,
      WeatherOverviewSlice,
      WeatherOverviewSliceDefaultPrimary,
      WeatherOverviewSliceVariation,
      WeatherOverviewSliceDefault,
    };
  }
}
