// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  centered_intro_search: dynamic(() => import("./CenteredIntroSearch")),
  search_bar: dynamic(() => import("./SearchBar")),
  weather_detail_list: dynamic(() => import("./WeatherDetailList")),
  weather_forecast: dynamic(() => import("./WeatherForecast")),
  weather_overview: dynamic(() => import("./WeatherOverview")),
};
